spring.application.name=LibraryAPI
#spring.profiles.active=dev

server.port=8080

## Conexão com a base de dados ##
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true

## JPA Configuration ##

# Tells Hibernate how to handle the database schema at application startup.
# The value 'validate' checks that the database matches the @Entity classes.
# Only validates fields that are mapped in the entity.
spring.jpa.hibernate.ddl-auto=validate