# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/springboot/application.properties to edit this template

server.port=8080

## Conexão com a base de dados ##
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
#spring.datasource.url=jdbc:postgresql://localhost:5432/library-db
spring.datasource.username=${DB_USER}
#spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.password=postgres

spring.flyway.enabled=true

## Configuração JPA ##

# Tells Hibernate how to handle the database schema at application startup.
# The value 'validate' checks that the database matches the @Entity classes.
# Only validates fields that are mapped in the entity.
spring.jpa.hibernate.ddl-auto=validate
# show sql statements issued by JPA
# Print all generated SQL queries to the console/logs.
# For Dev Env only, for production, it’s usually turned off and replaced with proper logging configuration.
spring.jpa.show-sql=true

# enable debug logging for spring boot and hibernate classes
# this is equivalent to passing '--debug' as command line argument
#logging.level.org.springframework.boot=DEBUG
#logging.level.org.hibernate.SQL=DEBUG

# log to file (absolute/relative path of log file)
#logging.file=path/to/log/file.log
